@startuml
!include _style.iuml
title アクティビティ図 UC2：チェックインする
|受付係|
start
:予約番号を入力する;
|HRS|
if (予約が存在するか？) then (しない)
  :「予約なし」を通知する;
  stop
else (する)
endif
if (予約は未利用か？) then (利用済)
  :「予約は利用済」を通知する;
  stop
else (未利用)
  :予約を利用済にする;
endif
if (在室状況が「不在」の部屋があるか？) then (なし)
  :「空室なし」を通知する;
  stop
else (あり)
  :在室状況が「不在」の部屋を 1 室、この予約に割り当てる;
  :割り当てた部屋の在室状況を「不在」から「在室」にする;
  :料金 8000 円を計上する（未精算）;
endif
|受付係|
:部屋番号を受け取る;
stop
@enduml
